# Generated by Django 4.1 on 2024-12-19 02:35

from django.db import migrations, models
import 鱼类环境DNA数据库.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_12S_info',
            fields=[
                ('cn_Species', models.CharField(blank=True, max_length=20)),
                ('cn_Order', models.CharField(blank=True, max_length=20)),
                ('cn_Family', models.CharField(blank=True, max_length=20)),
                ('Class', models.CharField(blank=True, max_length=200)),
                ('Order', models.CharField(blank=True, max_length=200)),
                ('Family', models.CharField(blank=True, max_length=200)),
                ('Genus', models.CharField(blank=True, max_length=200)),
                ('Species', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('IUCN', models.CharField(blank=True, max_length=20)),
                ('Endemic', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('distribution', models.TextField(blank=True, max_length=100)),
                ('fishbase_web', models.URLField(blank=True, null=True)),
                ('fasta_12S', models.FileField(blank=True, null=True, upload_to=鱼类环境DNA数据库.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='物种名',
            fields=[
                ('种名拉丁语', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('种曾用名拉丁语', models.CharField(blank=True, max_length=200)),
                ('种名中文', models.CharField(blank=True, max_length=20)),
                ('种曾用名中文', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
