# Generated by Django 4.1 on 2025-02-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('鱼类环境DNA数据库', '0004_delete_blasttask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_12s_info',
            name='cn_Class',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
