# Generated by Django 4.1 on 2024-12-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('鱼类环境DNA数据库', '0001_initial'),
    ]

    operations = [
    ]
