# Generated by Django 4.1 on 2024-12-23 01:46

from django.db import migrations, models
import 鱼类环境DNA数据库.models


class Migration(migrations.Migration):

    dependencies = [
        ('鱼类环境DNA数据库', '0002_auto_20241219_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('query_sequence', models.TextField(verbose_name='查询序列')),
                ('database', models.CharField(max_length=100, verbose_name='数据库')),
                ('e_value_threshold', models.FloatField(default=1e-05, verbose_name='E 值阈值')),
                ('max_hits', models.IntegerField(default=100, verbose_name='最大命中数')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='blast_results/', verbose_name='结果文件')),
            ],
        ),
        migrations.AlterField(
            model_name='all_12s_info',
            name='fasta_12S',
            field=models.FileField(default='default_fasta_sequence', upload_to=鱼类环境DNA数据库.models.get_upload_path),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='all_12s_info',
            index=models.Index(fields=['Species'], name='鱼类环境DNA数据库__Species_845a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='all_12s_info',
            index=models.Index(fields=['cn_Species'], name='鱼类环境DNA数据库__cn_Spec_14f98f_idx'),
        ),
        migrations.AddIndex(
            model_name='物种名',
            index=models.Index(fields=['种名拉丁语'], name='鱼类环境DNA数据库__种名拉丁语_4d3db7_idx'),
        ),
        migrations.AddIndex(
            model_name='物种名',
            index=models.Index(fields=['种名中文'], name='鱼类环境DNA数据库__种名中文_24f3bd_idx'),
        ),
    ]
