# Generated by Django 4.1 on 2025-02-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('鱼类环境DNA数据库', '0003_blasttask_alter_all_12s_info_fasta_12s_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlastTask',
        ),
        migrations.RemoveIndex(
            model_name='all_12s_info',
            name='鱼类环境DNA数据库__Species_845a1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='all_12s_info',
            name='鱼类环境DNA数据库__cn_Spec_14f98f_idx',
        ),
        migrations.RemoveIndex(
            model_name='物种名',
            name='鱼类环境DNA数据库__种名拉丁语_4d3db7_idx',
        ),
        migrations.RemoveIndex(
            model_name='物种名',
            name='鱼类环境DNA数据库__种名中文_24f3bd_idx',
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='Sub_cn_Family',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='Sub_cn_Genus',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='Sub_cn_Order',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='Sub_cn_Species',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='Subclass',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='Subfamily',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='Subgenus',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='Suborder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='Subspecies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='all_12s_info',
            name='cn_Genus',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='all_12s_info',
            name='fasta_12S',
            field=models.FileField(upload_to='fasta_files/'),
        ),
    ]
